# Linear Algebra

#### Importing Packages
Python has an extensive collection of third-party libraries, or ***packages***, with additional functions, data-structures, etc.  Many (most?) packages of interest are hosted on the Python Package Index ***pypi***, and can be installed into your environment using ***pip***.  The Anaconda distribution in the pre-work includes a number of these that are useful in data science, so you should have most of them installed already.  

ref:  https://pypi.python.org/pypi

A note on namespaces when importing - there are a few different ways to import:

    1. import numpy

    - all submodules of numpy are accessible in the numpy namespace
    - e.g. numpy.array([1,2,3])


    2. import numpy as np

    - same as 1 except an alias 'np' is created for the namespace instead
    - e.g. np.array([1,2,3])


    3. from numpy import *

    - adds all submodules to global namespace
    - e.g. array([1,2,3])
    - Note: This can be dangerous because if different modules have submodules with the same name than whatever is imported last will overrite what came before it - i.e. naming collision -> overwriting!.
    
    4. from numpy import array
    
    - will import only the indicated submodules into the global namespace
    - e.g. array([1,2,3])
    - Note: can be ok since you are being explicit
    
    We will generally use 2 and 4 (sparingly)

### NumPy

As we've seen in lecture, linear algebra is the branch of mathematics describing navigation between different vector spaces. This core concept is very important as various data science techniques rely upon it (e.g. Linear Regression, Support Vector Machines, Recommender Systems, Neural Networks).

NumPy is a package designed to be used in scientific computing, and specifically around building and manipulating N-dimensional array objects.

In [2]:
import numpy

import numpy as np

from numpy import absolute

# The next one is dangerous to do, and not recommended 
# except in cases where you know why you're using it
# from numpy import *

Now we can do the same thing three ways

In [ ]:
print numpy.absolute(-10)
print np.absolute(-10)
print absolute(-10)

We can create the Linear Algebra Objects we saw in lecture

In [ ]:
vector = np.array([1, 2, 1])

In [ ]:
data = np.array([[1, 2, 3],[2, 4, 9]])
data

In [ ]:
data[0]  # first row

In [ ]:
data[ : , 1]  # all rows, second column

Numpy lets us perform matrix operations

In [ ]:
np.dot(data, vector)

We can transpose an array

In [ ]:
print data
print data.T

#### Creating a square matrix array

In [ ]:
a = np.arange(25).reshape(5,5)
# arange(n) is a function that creates a 1 row array of integers of length n 
# reshape(M,N) is a method converts a list to a matrix of size MxN
a

In [ ]:
biga = a*10
biga

In [ ]:
print biga.mean()
print biga.mean(0) #Average per column
biga.mean(1) #average per row
# type(biga.mean(1))

Creating a matrix with numpy

In [ ]:
bigm = np.matrix(biga-20)
bigm

Creating the Inverse of a Matrix

In [ ]:
np.linalg.inv(biga-20)

#### Slices

In [ ]:
bigm = np.array(bigm)
print bigm
bigm[0]

In [ ]:
#Same thing, but demonstrating the full slice with a colon
print biga
biga[0,:]

#### Describing your Arrays

In [ ]:
compa = np.arange(30).reshape(5,3,2)
compa

In [ ]:
# lets describe it
print compa.shape
print compa.ndim
print compa.dtype

In [ ]:
compa[3,:,1]

In [ ]:
# We can assign values using list-like index
# But be careful on types
compa[0,0,0] = 5.9
compa[0,0,0

We can change the datatype when needed

In [ ]:
compa = compa.astype(float)
compa[0,0,0] = 5.75
compa[0,0,0]

#### Stacking arrays

You must stack using dimensions of the saem size

In [36]:
a = np.array((1,2,3))
b = np.array((2,3,4))
print 'H Stack'
print np.hstack((a,b))
print 'V Stack'
print np.vstack((a,b))

H Stack
[1 2 3 2 3 4]
V Stack
[[1 2 3]
 [2 3 4]]


In [37]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
print 'H Stack'
print np.hstack((a,b))
print 'V Stack'
print np.vstack((a,b))

H Stack
[[1 2]
 [2 3]
 [3 4]]
V Stack
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


### Using Random Numbers

Random numbers are very helpful and are necessary at times for testing data pipelines and running statistical analyses. Functions for creating random values are under numpy.random.

In [38]:
#Create a randomized array
rm = np.random.rand(5,5)
rm

array([[ 0.55211273,  0.02291274,  0.88483004,  0.4163007 ,  0.794886  ],
       [ 0.42604908,  0.39725043,  0.38803416,  0.64084183,  0.72135545],
       [ 0.83814379,  0.73982818,  0.44033049,  0.37719339,  0.99237314],
       [ 0.84047033,  0.52205681,  0.74068012,  0.89258891,  0.37383943],
       [ 0.50065524,  0.36245237,  0.53077972,  0.20083686,  0.82874197]])

In [ ]:
rm.shape

You can shuffle values randomly as well

In [39]:
# This will shuffle along the first index of a multi-dimensional array
np.random.shuffle(rm)
rm

array([[ 0.83814379,  0.73982818,  0.44033049,  0.37719339,  0.99237314],
       [ 0.42604908,  0.39725043,  0.38803416,  0.64084183,  0.72135545],
       [ 0.55211273,  0.02291274,  0.88483004,  0.4163007 ,  0.794886  ],
       [ 0.84047033,  0.52205681,  0.74068012,  0.89258891,  0.37383943],
       [ 0.50065524,  0.36245237,  0.53077972,  0.20083686,  0.82874197]])

In [40]:
print rm.mean()
print rm.mean(0) #Average per column
print rm.mean(1) #average per row

0.577021755754
[ 0.63148623  0.40890011  0.59693091  0.50555234  0.7422392 ]
[ 0.6775738   0.51470619  0.53420844  0.67392712  0.48469323]


In [41]:
# for a different Normal Distribution, use np.random.normal
rm = np.random.normal(5,9,(30,30))
rm

array([[  7.83264793e+00,   9.73625491e+00,  -6.82597708e+00,
          8.76992491e+00,   7.54258695e-01,  -3.54833256e+00,
          3.39540165e+00,   1.12815354e+00,   5.80738650e-01,
         -4.75318977e+00,   4.06255252e+00,   5.53252314e+00,
          1.23703840e+00,   8.78297520e+00,   4.12892521e+00,
         -5.83673943e+00,   2.30818470e+00,  -4.70042227e+00,
          1.28535884e+00,   1.11540575e+01,  -1.07920503e+01,
          5.10632302e-01,  -7.39360412e+00,   1.67159760e+01,
          1.14083917e+01,   1.33422680e+01,   1.62283368e+01,
         -1.04448532e+01,  -2.89360008e+00,  -3.47488034e+00],
       [ -2.47614709e+00,  -9.73466118e+00,   2.97055251e+00,
          1.50192528e+01,   1.68694503e+00,   1.08081088e+01,
          2.20855439e+01,   1.61988542e+01,   1.78559178e+01,
          6.02531797e+00,   1.38970140e+01,   1.05879632e+01,
         -8.96287820e+00,   1.19668738e-01,  -1.25541922e+01,
          2.86231392e+00,  -1.55720397e+01,   1.58024817e+01,
       

In [42]:
print rm.mean(), "which is hopefully close to the input mean"
print rm.var(), "which variance = stdev squared"
print np.median(rm)

5.16946119332 which is hopefully close to the input mean
82.2301284372 which variance = stdev squared
5.31197003627


Find more distributions and random functions here: http://docs.scipy.org/doc/numpy/reference/routines.random.html

### Exercise 1

1) Create a 4x5 array of integers between 0 and 19

In [7]:
a = np.arange(20).reshape(4,5)
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


2) Create a 50x500 array with a mean of 20 and variance of 100. Save it to a variable called  biggie

In [31]:
biggie=np.random.normal(20,10,(50,500))
biggie.mean()

20.012193247132373

3) Change the mean of the array to a value within 1 of 0 and the variance within 1 of 25. Think about what the mean and the variance represent and try using various mathematical operations.

In [32]:
b2=(biggie-19.5)/2
print b2.mean()
print b2.var()


0.256096623566
25.0502075552


## Pandas (python package)

Pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive.

Pandas is great for tabular/indexed data

In [33]:
# NOTE: you should normally put all your imports at the top of the file
import pandas as pd

In [34]:
data = pd.read_csv('../data/nytimes.csv')

In [35]:
# Note here we're calling the head method on the dataframe to return the 'head' of the 
# dataframe, in this case the first 4 lines
# head() actually creates a new copy of the data, this is important later in the course!
data.head(4)

Age  Gender  Impressions  Clicks  Signed_In
0   36       0            3       0          1
1   73       1            3       0          1
2   30       0            3       0          1
3   49       1            3       0          1

In [ ]:
data[0:4]

In [43]:
# Each DataFrame has an index
# Sometimes you will need to reindex
data.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9, 
            ...
            458431, 458432, 458433, 458434, 458435, 458436, 458437, 458438,
            458439, 458440],
           dtype='int64', length=458441)

In [ ]:
# This is a Series
# A DataFrame is made of of several Series with the same index
data.Age

In [ ]:
data.info()

In [ ]:
data.describe()

In [ ]:
# We can change this data into numpy
type(data.Age.values)

#### Just like in numpy, we can use mean, var, and other functions on the data

In [ ]:
print data.Age.mean()
print data.Age.var()
print data.Age.max()
print data.Age.min()

In [44]:
# Function that groups users by age.
def map_age_category(x):
    if x < 18:
        return '1'
    elif x < 25:
        return '2'
    elif x < 32:
        return '3'
    elif x < 45:
        return '4'
    else:
        return '5'

data['age_categories'] = data['Age'].apply(map_age_category)

In [45]:
data.head()

Age  Gender  Impressions  Clicks  Signed_In age_categories
0   36       0            3       0          1              4
1   73       1            3       0          1              5
2   30       0            3       0          1              3
3   49       1            3       0          1              5
4   47       1           11       0          1              5

#### Sorting data

In [ ]:
data.sort_index(axis=1, ascending=False).head()

In [ ]:
data.sort('Signed_In').head()

In [46]:
ran_data = [
    ['a', 1]
    , ['b', 2]
    , ['c', 3]
]
df = pd.DataFrame(ran_data, columns=['col_a', 'numeric'])
df

col_a  numeric
0     a        1
1     b        2
2     c        3

#### Indexing functions

Pandas Dataframes support various methods for indexing:

- .iloc
- .loc
- .ix

In [47]:
df

col_a  numeric
0     a        1
1     b        2
2     c        3

In [48]:
# iloc accesses a row by its row number
df.iloc[0]

col_a      a
numeric    1
Name: 0, dtype: object

In [49]:
df.set_index('col_a', inplace = True)
df

numeric
col_a         
a            1
b            2
c            3

In [50]:
# loc accesses a dataframe row by its index label (or column label)
df.loc['a'] = 5
df.loc['b'] = 3

In [ ]:
df

In [51]:
# This can be used to add new columns
df.loc[:,'C'] = df.loc[:,'numeric']

df

numeric  C
col_a            
a            5  5
b            3  3
c            3  3

In [52]:
# is equivalent to:
df['D'] = df.loc[:,'numeric']

df

numeric  C  D
col_a               
a            5  5  5
b            3  3  3
c            3  3  3

.ix is the generic form of indexers

Values can be set by index and index + column

In [54]:
df.ix[2] = 2
df.ix[2, 'C'] = 3

df

numeric  C  D
col_a               
a            5  5  5
b            3  3  3
c            2  3  2

### Combining DataFrames
#### Appending
We can append dataframes together

In [55]:
df_combine = df.append(df)
df_combine

numeric  C  D
col_a               
a            5  5  5
b            3  3  3
c            2  3  2
a            5  5  5
b            3  3  3
c            2  3  2

In [56]:
# When DataFrames are appended together, we often need to create a new index
df_combine.reset_index()

col_a  numeric  C  D
0     a        5  5  5
1     b        3  3  3
2     c        2  3  2
3     a        5  5  5
4     b        3  3  3
5     c        2  3  2

#### Join lets us join together dataframes using their index

In [57]:
df_2 = pd.DataFrame([1, 2, 3], columns=['col'])
df_2

col
0    1
1    2
2    3

In [58]:
# The default is left join, so Null values are placed
# where values are misssing
df.join(df_2)


numeric  C  D  col
col_a                    
a            5  5  5  NaN
b            3  3  3  NaN
c            2  3  2  NaN

In [59]:
# reset the index
df_1 = df.reset_index()
df_1

col_a  numeric  C  D
0     a        5  5  5
1     b        3  3  3
2     c        2  3  2

In [60]:
# try joining again:
df_1.join(df_2)


col_a  numeric  C  D  col
0     a        5  5  5    1
1     b        3  3  3    2
2     c        2  3  2    3

#### Merge allows us to join on any fields

In [ ]:
# Merge has a default of inner join
# So where the join misses rows are omitted
df.merge(df_2, left_on='numeric', right_on='col')

### Concat combines a list of DataFrames together

In [61]:
# It can be used like append
pd.concat([df, df])

numeric  C  D
col_a               
a            5  5  5
b            3  3  3
c            2  3  2
a            5  5  5
b            3  3  3
c            2  3  2

In [62]:
# But concat will create a spare DataFrame when columns don't match
# This can create huge dataframes when mismatches occur
pd.concat([df, df_2])

C   D  col  numeric
col_a                      
a       5   5  NaN        5
b       3   3  NaN        3
c       3   2  NaN        2
0     NaN NaN    1      NaN
1     NaN NaN    2      NaN
2     NaN NaN    3      NaN

## Exercise 2
### Combining numpy and pandas

1) Create 2 arrays of integers

One should be created using np.random

In [73]:
a1 = np.random.rand(4,4)
a2=np.array([1, 2, 1])
print a1,a2

[[ 0.82475776  0.99850137  0.54420457  0.28169601]
 [ 0.3273314   0.86888112  0.21332459  0.6466872 ]
 [ 0.46189256  0.47824419  0.0206      0.11036246]
 [ 0.0881325   0.42721967  0.30069715  0.85102189]] [1 2 1]


2) Turn those arrays into pandas DataFrames

The columns can be named numerically

In [74]:
a1_pd=pd.DataFrame(a1)
a2_pd=pd.DataFrame(a2)
print a1_pd, a2_pd

          0         1         2         3
0  0.824758  0.998501  0.544205  0.281696
1  0.327331  0.868881  0.213325  0.646687
2  0.461893  0.478244  0.020600  0.110362
3  0.088132  0.427220  0.300697  0.851022    0
0  1
1  2
2  1


3) Use some of the summary functions on the dataframes and arrays

Show how mean and var give the same response in python and numpy

In [75]:
print a1.mean()
print a1_pd.mean().mean()

0.465222152885
0.465222152885



4) Add an extra index using .loc

5) Using merge or join, create a single DataFrame from the two

6) Try testing out the groupby functions

df.groupby(column).agg (agg can be an aggregate function, try sum, max, min...)

Resources can be found here: http://pandas.pydata.org/pandas-docs/stable/10min.html#grouping


## Plotting!

In [ ]:
import pandas.io.data
import datetime
import matplotlib.pyplot as plt

%matplotlib inline

mu, sigma = 0, 0.1
normal_dist = np.random.normal(mu, sigma, 1000)
aapl = pd.io.data.get_data_yahoo('FB', 
                                 start=datetime.datetime(2015, 4, 1), 
                                 end=datetime.datetime(2015, 4, 28))
aapl.head()

## MatPlotLib

MatPlotLib is a standard, granular method for building visualizations. Although tried and true, it can be cumbersome compared to other higher level packages such as Seaborn or Bokeh. Note most visualization packages use matplotlib as their base.

In [ ]:
fig = plt.figure(figsize=(20,16))

ax = fig.add_subplot(2,2,1)
ax.plot(aapl.index, aapl['Close'])
ax.set_title('Line plots', size=24)

ax = fig.add_subplot(2,2,2)
ax.plot(aapl['Close'], 'o')
ax.set_title('Scatter plots', size=24)

ax = fig.add_subplot(2,2,3)
ax.hist(normal_dist, bins=50)
ax.set_title('Histograms', size=24)
ax.set_xlabel('count', size=16)

ax = fig.add_subplot(2,2,4)
ax.boxplot(normal_dist)
ax.set_title('Boxplots', size=24)

### Bokeh
To install Bokeh, go to a terminal and type:

`conda install bokeh` 

Bokeh is built by the same people that created Anaconda (Continuum Analytics) and is designed out of the box for web display, making it nice for creating presentation ready, interactive visuals quickly. Labs in this course will be shown in Bokeh. Checkout http://bokeh.pydata.org/en/latest/docs/quickstart.html#concepts to see some of the range of capabilities.

In [ ]:
from bokeh.plotting import figure, output_notebook,show
output_notebook()

In [ ]:
# prepare some data
x = aapl.Low
y = aapl['High']

# create a new plot with a title and axis labels
p = figure(title="Stock High vs. Low", x_axis_label='Low', y_axis_label='High')

# add a line renderer with legend and line thickness
p.circle(x, y, legend="High vs. Low", line_width=2)

# show the results
show(p)

In [ ]:
x = aapl.index
y = aapl.Close
p = figure(title="Stock Open & Close over time", x_axis_label='Date', y_axis_label='High',x_axis_type="datetime")
# Note that I've declared the x_axis_type
p.square(x, y, legend="Close")
p.circle(x,aapl.Open,legend='Open',color='red')
# show the results
show(p)

## Pandas Plotting!

The plot method is a great, quick way to visualize your dataframes. By selecting the columns you care to view, calling .plot() on the dataframe defaults to a line chart vs. the index.

We will be revisiting this so just take a second to appreciate what can be done with one line of code.

In [ ]:
aapl[['Open','Close']].plot()

In [ ]:
aapl[['High','Low','Open','Close']].plot(kind='box')