


Cross Validation & Naive Bayes Lab - SMS Spam Classification
===============
* orignally developed by Ankit Jain
* modified by Justin Breucop
* modified by Dylan Hercher

Data source: https://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection

# Section 1)

## Cross Validation from Scratch

Let's build it the function together! The steps to cross validation are:
1. Randomly separate your training set into _k_ groups
2. For each group _k_:
>1. Train your model on the other groups
>2. Score your model using group _k_ as validation
>3. Save your score and move to your next group

3. Add your _k_ scores and divide by _k_ to get your average score

In [1]:
# Importing Packages 
import numpy as np
import pandas as pd

from sklearn.neighbors import KNeighborsClassifier

In [45]:
model = KNeighborsClassifier(10)

df = pd.DataFrame.from_csv('../data/titanic-train.csv',index_col=None)[['Age','Pclass','SibSp','Survived']].dropna()
to_predict = "Survived"
features=['Age','Pclass','SibSp']
data = df[features]
label = df[to_predict]
folds=5


Let's build in class!

In [ ]:
#Function here:
def cross_validate_df(data,label,model,k):
    x=len(df)
    for i in range(0,k-1):
        i1=i*x/k
        i2=(i+1)*x/k-1
        y_train=df[]
        myknn = KNeighborsClassifier(3).fit(X_train,y_train)
    """Return Average score across k iterations
    Parameters
    -----------
    data : DataFrame with features to use in X
    label : Series with target y
    model : ML Model to use
    k : int number of iterations
    """
    # TODO: Design the cross validation function
    # it may be helpful to try writing the function with k=1 first
    
    return None

In [ ]:
# Once Complete test your function here
cross_validate_df(data,label,model,5)

### Built-in Cross Validation
There is also a very simple cross validation function provided by sklearn

In [ ]:
from sklearn.cross_validation import cross_val_score

# Results of using the built-in cross validation
# Note: Default is Kfold, but within sklearn.cross_validation
# there are many types of validation that can be used
cross_val_score(model, data, label, cv=3)

In [ ]:
cross_val_score(model, data, label, cv=3)

In [ ]:
np.mean(cross_val_score(model, data, label, cv=3))

# Section 2)
## Naive Bayes and SMS Spam Classification

In [12]:
import numpy as np
import pandas as pd

from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics


In [58]:
## READING IN THE DATA
df = pd.DataFrame.from_csv("../data/SMSSpamCollection.tsv",sep='\t',header=0,index_col=None)

In [59]:
# examine the data
df.head()

label                                                msg
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [60]:
df[df.label=='spam'].head()

label                                                msg
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
5   spam  FreeMsg Hey there darling it's been 3 week's n...
8   spam  WINNER!! As a valued network customer you have...
9   spam  Had your mobile 11 months or more? U R entitle...
11  spam  SIX chances to win CASH! From 100 to 20,000 po...

In [17]:
df.label.value_counts()

ham     4825
spam     747
dtype: int64

In [61]:
df.msg.describe()

count                       5572
unique                      5169
top       Sorry, I'll call later
freq                          30
Name: msg, dtype: object

In [62]:
# Convert the label into a binary variable
# Remember the map function we learned before?
df['label'] = df.label.map({'ham': 0 , 'spam':1})

In [63]:
df.head()

label                                                msg
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [64]:
# split into training and testing sets by calling sklearn lib
# by default, the data set is split into 0.75 (training) and 0.25 (testing)
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.msg, df.label, random_state=1)

In [65]:
print X_train.shape
print X_train

(4179,)
710     4mths half price Orange line rental & latest c...
3740                           Did you stitch his trouser
2711    Hope you enjoyed your new content. text stop t...
3155    Not heard from U4 a while. Call 4 rude chat pr...
3748    Ü neva tell me how i noe... I'm not at home in...
2389    wiskey Brandy Rum Gin Beer Vodka Scotch Shampa...
3464    i am seeking a lady in the street and a freak ...
772     Lol! U drunkard! Just doing my hair at d momen...
3667    I'm turning off my phone. My moms telling ever...
4955    U coming back 4 dinner rite? Dad ask me so i r...
854     AH POOR BABY!HOPE URFEELING BETTERSN LUV! PROB...
4079                  Gam gone after outstanding innings.
2837                         Nice.nice.how is it working?
1392                  Haha just kidding, papa needs drugs
5533    Hey chief, can you give me a bell when you get...
874     Ugh its been a long day. I'm exhausted. Just w...
4408    Awesome, plan to get here any time after like ...
3990  

In [48]:
X_test.shape

(1393,)

Now we need to convert the text into feature vectors which can be used for machine learning purposes.
We will use the scikit function of CountVectorizer to 'convert text into a matrix of token counts'

 http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

#### Lets try a simple example

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
# start with a simple example
train_simple = ['call you tonight',
                'Call me a cab',
                'please call me... PLEASE!']

In [ ]:
# learn the 'vocabulary' of the training data
vect = CountVectorizer(decode_error='ignore')
vect.fit(train_simple)
vect.get_feature_names()

In [ ]:
# transform training data into a 'document-term matrix'
train_simple_dtm = vect.transform(train_simple)
train_simple_dtm.toarray()

In [ ]:
# We can see how we've adjusted our data easily!
# examine the vocabulary and document-term matrix together
print train_simple
    
pd.DataFrame(train_simple_dtm.toarray(), columns=vect.get_feature_names())

In [ ]:
# transform testing data into a document-term matrix (using existing vocabulary)
test_simple = ["please don't call me"]
test_simple_dtm = vect.transform(test_simple)
test_simple_dtm.toarray()

pd.DataFrame(test_simple_dtm.toarray(), columns=vect.get_feature_names())

#### Question:  How does the above test_simple show how things can go wrong?

#### Exercise: Using the dataset below
   * Vectorize the text
   * Store the results in a DataFrame
   * Show word counts (hint: one dataframe describer can do this)
   * Transform the test text

In [23]:
train_exp = ['where is my taco?',
                'did I eat the taco',
                'I can easily eat my way through that whole box of tacos!',
                'I think way too much about tacos, huh',
                'taco, taco, taco!!!'                
               ]
test_exp = [
    'where did he go?', 'how long did the whole thing last', 'lets go eat one taco or multiple tacos'
]

In [32]:
# learn the 'vocabulary' of the training data
vect = CountVectorizer(decode_error='ignore')
vect.fit(train_exp)
vect.get_feature_names()
train_simple_dtm = vect.transform(train_exp)
train_simple_dtm.toarray()
test=vect.transform(test_exp)
test.toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

## Vectorizing our SMS Dataset

In [73]:
# instantiate the vectorizer ( use variable name as vect)
vect = CountVectorizer(decode_error = 'ignore')
vect.fit(train_exp)
vect.get_feature_names()

[u'about',
 u'box',
 u'can',
 u'did',
 u'easily',
 u'eat',
 u'huh',
 u'is',
 u'much',
 u'my',
 u'of',
 u'taco',
 u'tacos',
 u'that',
 u'the',
 u'think',
 u'through',
 u'too',
 u'way',
 u'where',
 u'whole']

In [67]:
# transform testing data into a document-term matrix: Use Variable name as test_dtm
train_dtm = vect.transform(X_train)
test_dtm = vect.transform(X_test)
print test_dtm

  (0, 14)	1
  (10, 9)	1
  (11, 9)	1
  (13, 7)	1
  (13, 10)	1
  (13, 14)	1
  (14, 2)	1
  (14, 9)	1
  (16, 9)	1
  (17, 14)	1
  (17, 18)	1
  (19, 13)	1
  (20, 2)	1
  (20, 9)	1
  (21, 2)	1
  (21, 7)	1
  (22, 0)	1
  (22, 14)	1
  (23, 13)	1
  (25, 7)	1
  (26, 19)	1
  (28, 7)	3
  (28, 14)	1
  (29, 2)	1
  (29, 7)	1
  :	:
  (1357, 0)	1
  (1361, 7)	1
  (1361, 9)	1
  (1361, 10)	1
  (1366, 9)	1
  (1367, 2)	1
  (1371, 7)	1
  (1373, 3)	1
  (1373, 15)	1
  (1373, 17)	1
  (1374, 7)	1
  (1374, 9)	1
  (1374, 13)	1
  (1374, 18)	1
  (1375, 10)	1
  (1377, 7)	1
  (1377, 14)	1
  (1378, 2)	1
  (1378, 7)	1
  (1378, 14)	1
  (1383, 7)	1
  (1383, 14)	2
  (1385, 7)	1
  (1385, 9)	1
  (1390, 7)	1


In [70]:
# Get the length and names of the feature names
train_features = vect.get_feature_names()
len(train_features)

21

In [71]:
train_features[:50]

[u'about',
 u'box',
 u'can',
 u'did',
 u'easily',
 u'eat',
 u'huh',
 u'is',
 u'much',
 u'my',
 u'of',
 u'taco',
 u'tacos',
 u'that',
 u'the',
 u'think',
 u'through',
 u'too',
 u'way',
 u'where',
 u'whole']

In [72]:
train_features[-50:]

[u'about',
 u'box',
 u'can',
 u'did',
 u'easily',
 u'eat',
 u'huh',
 u'is',
 u'much',
 u'my',
 u'of',
 u'taco',
 u'tacos',
 u'that',
 u'the',
 u'think',
 u'through',
 u'too',
 u'way',
 u'where',
 u'whole']

In [56]:
# convert train_dtm to a regular array
train_arr = train_dtm.toarray()
train_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [51]:

# Revisit Numpy
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print arr[0, 0]
print arr[1, 3]
print arr[0, :]
print arr[:, 0]
print np.sum(arr)
print np.sum(arr,axis = 0)
print np.sum(arr,axis = 1)




1
8
[1 2 3 4]
[1 5]
36
[ 6  8 10 12]
[10 26]


In [57]:
# exercise: calculate the number of tokens in the 0th message in train_arr
print np.sum(train_arr[0,:])

0


In [ ]:

# exercise: count how many times the 0th token appears across ALL messages in train_arr
print np.sum(train_arr[:,0])

In [ ]:
# exercise: count how many times EACH token appears across ALL messages in train_arr
print np.sum(train_arr, axis=0)

In [ ]:
# exercise: create a DataFrame of tokens with their counts.


### Let's build the model with Naive Bayes Now

http://scikit-learn.org/stable/modules/naive_bayes.html

In [ ]:
# train a Naive Bayes model using train_dtm
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(train_dtm, y_train)

In [ ]:
# make predictions on test data using test_dtm
preds = nb.predict(test_dtm)
preds

In [ ]:
# compare predictions to true labels
from sklearn import metrics
print metrics.accuracy_score(y_test, preds)
print metrics.confusion_matrix(y_test, preds)

# confusion matrix: http://en.wikipedia.org/wiki/Confusion_matrix

In [ ]:
# exercise: show the message text for the false positives
X_test[(y_test == 0) & (preds == 1)]

In [ ]:
# exercise: show the message text for the false negatives
X_test[y_test > preds]
# or
X_test[(y_test == 1) & (preds == 0)]

In [ ]:
## USING ALL DATA AND CROSS-VALIDATION, run NB again


In [74]:
# Here is the condensed code needed for reference
df = pd.DataFrame.from_csv("../data/SMSSpamCollection.tsv",sep='\t',header=0,index_col=None)
X_train, X_test, y_train, y_test = train_test_split(df.msg, df.label, random_state=1)
df.label=df.label.map({'ham':00,'spam':1})
vect = CountVectorizer(decode_error = 'ignore')

vect.fit(X_train)
vect.get_feature_names()

train_dtm = vect.transform(X_train)
test_dtm = vect.transform(X_test)

In [75]:
len(vect.get_feature_names())
## EXERCISE: CALCULATE THE 'SPAMMINESS' OF EACH TOKEN

# create separate DataFrames for ham and spam ( df_ham and df_spam)


7456

In [ ]:
# learn the vocabulary of ALL messages and save it


In [ ]:
# create document-term matrix of ham, then convert to a regular array


In [ ]:
# create document-term matrix of spam, then convert to a regular array


In [ ]:
# count how many times EACH token appears across ALL messages in ham_arr


In [ ]:
# count how many times EACH token appears across ALL messages in spam_arr


In [ ]:
# create a DataFrame of tokens with their separate ham and spam counts


In [ ]:
# add one to ham counts and spam counts so that ratio calculations (below) make more sensse


In [ ]:
# calculate ratio of spam-to-ham for each token


In [ ]:
# advanced: implement your own naive bayes classifier
